# 基础镜像
FROM redis
# author
MAINTAINER leitianyu

# 挂载目录
VOLUME /home/leitianyu/redis
# 创建目录
RUN mkdir -p /home/leitianyu/redis
# 指定路径
WORKDIR /home/leitianyu/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/leitianyu/redis/redis.conf
