# 基础镜像
FROM nginx
# author
MAINTAINER leitianyu

# 挂载目录
VOLUME /home/leitianyu/projects/leitianyu-ui
# 创建目录
RUN mkdir -p /home/leitianyu/projects/leitianyu-ui
# 指定路径
WORKDIR /home/leitianyu/projects/leitianyu-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/leitianyu/projects/leitianyu-ui
