# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER leitianyu

# 挂载目录
VOLUME /home/leitianyu
# 创建目录
RUN mkdir -p /home/leitianyu
# 指定路径
WORKDIR /home/leitianyu
# 复制jar文件到路径
COPY ./jar/leitianyu-modules-file.jar /home/leitianyu/leitianyu-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","leitianyu-modules-file.jar"]
